#import sys
#Open HOST1 file where we are going to write the final output
HOST1 = '/home/ngull/Documents/GIT/ngull/local files/HOST1.txt'
outF = open(HOST1, "a")
#Open ipfile2 and split the lines to read each individually
with open("ipfile2.txt", "r") as f:
    ip1 = f.read().splitlines()
#For each IP on ipfile2 write the following (this would be JSON structure)
for ip in ip1:
    outF.write(" {\n")
    outF.write(' "l3extSubnet": {\n')
    outF.write(' "attributes": {\n')
    outF.write(' "aggregate": "",\n')
    outF.write(' "annotation": "",\n')
    outF.write(' "descr": "",\n')
    outF.write('"ip": ' + ip + ',\n')
    outF.write('"name": "N-MS-OFFICE-365",\n')
    outF.write('"nameAlias": "",\n')
    outF.write('"scope": "import-security"\n')
    outF.write(' }\n')
    outF.write(' }\n')
    outF.write(' },\n')
#Print on console as well just in case :)
    print(" {")
    print(' "l3extSubnet": {')
    print(' "attributes": {')
    print(' "aggregate": "",')
    print(' "annotation": "",')
    print(' "descr": "",')
    print('"ip": ' + ip + ',')
    print('"name": "N-MS-OFFICE-365",')
    print('"nameAlias": "",')
    print('"scope": "import-security"')
    print(' }')
    print(' } ')
    print(' },')
#Be a good boy and close your files :)
outF.close()
f.close()
